FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build

WORKDIR /app

COPY ["BalanceBoard.csproj", "./"]

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet restore BalanceBoard.csproj
	
COPY . .

ARG TARGETARCH

RUN --mount=type=cache,id=nuget,target=root/.nuget.packages \
    dotnet publish -c Release -o /app/publish_output -r linux-musl-${TARGETARCH/amd64/x64} --self-contained false

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS final
WORKDIR /app

RUN apk add --no-cache libpq

COPY --from=build /app/publish_output .

COPY entrypoint.sh .
RUN chmod +x entrypoint.sh

COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh

ENTRYPOINT ["./entrypoint.sh"]

USER $APP_UID
EXPOSE 80